app:
  name: My App
  description: Welcome to ${app.name}
my:
 greetings: Hello Greetings
 list: Hello, this, is, comma, seperated, list

db:
 connection: "{connectionstring: 'http://___', username: 'foo', password: 'password'}"
 host: 8769
 port: 1200

management.endpoints.web.exposure.include: "*"

spring.profiles.active: test