app:
  name: My App
  description: Welcome to ${app.name}
my:
 greetings: Hello Greetings
 list: Hello, this, is, comma, seperated, list
db:
  connection: "Connection-string"
  host: 8769
  port: 2400
management.endpoints.web.exposure.include: "*"

spring.config.import: "optional:configserver:http://localhost:8888"
spring.application.name: spring-boot-config